ITI.Ecommerce.Presenation/Controllers/CategoryController.cs
using DTOs;
using ITI.Ecommerce.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ITI.Ecommerce.Presenation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryServie _categoryServie;

        public CategoryController(ICategoryServie categoryServie)
        {
            _categoryServie = categoryServie;
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryDto categoryDto)
        {
            await _categoryServie.add(categoryDto);
            return RedirectToAction("GetAllCategories");
        }

        [HttpGet]
        public async Task<IActionResult> GetAllCategories()
        {
            var categories = await _categoryServie.GetAll();
            return View(categories);
        }
        [HttpGet]
        public async Task<IActionResult> GetCategoryByID()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetCategoryByID(int ID)
        {
            var category = await _categoryServie.GetById(ID);
            ViewBag.Done=true;
            return View(category);
        }
      
        public IActionResult Delete(CategoryDto categoryDto)
        {
            _categoryServie.Delete(categoryDto);
            return RedirectToAction("GetAllCategories");
        }
       
        public IActionResult CDelete(int id)
        {
            _categoryServie.CDelete(id);
            
            return RedirectToAction("GetAllCategories");
        }
        [HttpGet]
        public async Task<IActionResult> UpDate(int id)
        {
            var category = await _categoryServie.GetById(id);
            return View(category);
        }
     
        [HttpPost]
        public IActionResult CUpDate(CategoryDto categoryDto)
        {
            
            _categoryServie.Update(categoryDto);
            return RedirectToAction("GetAllCategories");
        }

        

        [HttpGet]
        public async Task<IActionResult> GetAllDeletedCategories()
        {
            var categories = await _categoryServie.GetAllDeleted();
            return View(categories);
        }

        public IActionResult Restore(int id)
        {
            _categoryServie.Restore(id);
            return RedirectToAction("GetAllCategories");
        }
    }
}

ITI.Ecommerce.Presenation/Controllers/OrderController.cs
using DTOs;
using ITI.Ecommerce.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace ITI.Ecommerce.Presenation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;
        private readonly IPaymentService _paymentService;
       

        public OrderController(IOrderService orderService , ICustomerService customerService, IPaymentService paymentService)
        {
            _orderService = orderService;
            _customerService = customerService;
            _paymentService = paymentService;
           
        }

       

        public async Task<IActionResult> GetAllOrders()
        {
            var Orders = await _orderService.GetAll();
            return View(Orders);
        }
        [HttpGet]
        public async Task<IActionResult> GetOrderyByID()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetOrderyByID(int ID)
        {
            var Order = await _orderService.GetById(ID);
            ViewBag.Done = true;
            return View(Order);
        }


        public IActionResult Delete(int id)
        {
            _orderService.Delete(id);
            return RedirectToAction("GetAllOrders");
        }
      

        [HttpGet]
        public async Task<IActionResult> GetAllDeliveredOrder()
        {

            var Orders = await _orderService.GetAllDelivered();
            return View(Orders);
        }
        [HttpGet]
        public async Task<IActionResult> GetAllPendingOrder()
        {

            var Orders = await _orderService.GetAllPending();
            return View(Orders);
        }

        public ActionResult Delivered(int id)
        {

            _orderService.ChangeToDelivered(id);
            return RedirectToAction("GetAllDeliveredOrder");
        }


       
        public ActionResult Index()
        {
            return View();
        }
    }
}

ITI.Ecommerce.Presenation/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ITI.Ecommerce.Presenation.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> RoleManager;
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            RoleManager = roleManager;
        }


        [HttpGet]
        public IActionResult Add()
        {

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Add(RoleCreateModel model)
        {

            if (ModelState.IsValid == false)
                return View();
            else
            {
                var result =
                await RoleManager.CreateAsync(
                    new IdentityRole
                    {
                        Name = model.Name
                    });
                if (result.Succeeded == false)
                {
                    result.Errors.ToList().ForEach(i =>
                    {
                        ModelState.AddModelError("", i.Description);
                    });
                    return View();
                }
                else
                {
                    return RedirectToAction("Home", "index");
                }

            }
        }
    }
}

ITI.Ecommerce.Presenation/Views/Shared/_Header.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer localizer

@inject SignInManager<Customer> UserManager;
@if (UserManager.IsSignedIn(User) == true && User.IsInRole("Admin"))
{
    <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
        <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
            <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
        </a>
        <a href="#" class="sidebar-toggler flex-shrink-0">
            <i class="fa fa-bars"></i>
        </a>
       
        <div class="navbar-nav align-items-center ms-auto">
            <div class="mt-3">
                <partial  name="_SelectLanguage" />
            </div>
            <div class="nav-item dropdown">

                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">

                    <img class="rounded-circle me-lg-2" src="~/Content/images/StaticImages/admin.png" alt="" style="width: 40px; height: 40px;">
                    <span>@User.Identity.Name</span>


                </a>
                
                <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                    <a asp-controller="User" asp-action="SignOut">@localizer["Sign Out"]</a>
                </div>
            </div>
        </div>
    </nav>
}
<!-- Navbar End -->

ITI.Ecommerce.Presenation/Views/Shared/_Layout.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization

@{
    var isRTL = CultureInfo.CurrentCulture.Name.StartsWith("ar");
}



@*<html >*@
   @* <html lang="en" dir="@(isRTL ? "RTL" : "LTR")">*@
    <head>

    <meta charset="utf-8">
    <title>B-TECH Admain Dash Board</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">


   @* Bootstrap  right to left  cdn*@

    @*@if (isRTL)
    {
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    }*@

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/content/css/bootstrap.min.css" rel="stylesheet">
    

    <!-- Template Stylesheet -->
        <link href="~/content/css/style.css" rel="stylesheet"/>

   </head>
    <body>

      

       <div class="container-xxl position-relative bg-white d-flex p-0">

        <!-- Sidebar -->
        <partial   name="_SideBar"></partial>

        <!-- Content Start -->

        <div class="content">

            <!--Header Navbar -->
            <partial  name="_Header"></partial>

                <div dir="@(isRTL ? "RTL" : "LTR")">@RenderBody()</div>
          

        </div>


        </div>
      
    


        

    <footer>

    </footer>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/content/lib/chart/chart.min.js"></script>
    <script src="~/content/lib/easing/easing.min.js"></script>
    <script src="~/content/lib/waypoints/waypoints.min.js"></script>
    <script src="~/content/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/content/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/content/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/content/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/content/js/main.js"></script>

    <script src="~/Contents/Content/lib/jquery/jquery.min.js"></script>
    <script src="~/Contents/Content/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/Contents/Content/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Contents/Content/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>

   </body>

</html>
 

ITI.Ecommerce.Presenation/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Http.Features;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.Extensions.Options;



@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultures = options.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div>
    <form method="post" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl">
        <select name="culture" class="form-select"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultures"
                onchange="this.form.submit();">
        </select>
    </form>
</div>

ITI.Ecommerce.Presenation/Views/Shared/_SideBar.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer localizer

@inject SignInManager<Customer> UserManager;

@if (UserManager.IsSignedIn(User) == true && User.IsInRole("Admin"))
{
    
    <div  class="sidebar pe-4 pb-3 ">
        <nav class="navbar bg-light navbar-light ">
            <a asp-controller="Home" asp-action="index" class="navbar-brand mx-4 mb-3">
                <h3 style="color:#0d6efd">B-TECH</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">

                    <div class="ms-3">
                        <h6 class="mb-0">Admin</h6>
                    </div>
                </div>
            <div class="navbar-nav w-100">
                <div class="nav-item dropdown">

                    @*Category Options*@
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-tags-fill me-2"></i>@localizer["Categories"]</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Category" asp-action="Add" class="nav-item nav-link"><i class="bi bi-plus-circle-fill me-2"></i>@localizer["Add New Category"]</a>
                            <a asp-controller="Category" asp-action="GetAllCategories" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>@localizer["View All Category"]</a>
                            <a asp-controller="Category" asp-action="GetAllDeletedCategories" class="nav-item nav-link"><i class="bi bi-x-circle-fill me-2"></i>@localizer["Deleted Category"]</a>

                      </div>
                    </div>
                        @*Product Options*@
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-diagram-3-fill me-2"></i>@localizer["Products"]</a>
                            <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Product" asp-action="Add" style="font-size:.9rem;" class="nav-item nav-link "><i class="bi bi-plus-circle-fill me-2"></i>@localizer["Add New Product"]</a>
                            <a asp-controller="Product" asp-action="GetAll" style="font-size:.9rem;" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>@localizer["View All Products"]</a>
                            <a asp-controller="Product" asp-action="AddProductImages" style="font-size:.95rem;" class="nav-item nav-link"><i class="bi bi-image-fill me-2"></i>@localizer["Add New Images"]</a>
                            <a asp-controller="Product" asp-action="GetAllDeleted" style="font-size:.95rem;" class="nav-item nav-link"><i class="bi bi-x-circle-fill me-2"></i>@localizer["Deleted Products"]</a>
                            </div>
                        </div>
                            @*Order Options*@
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-cart-fill me-2"></i>@localizer["Orders"]</a>
                            <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Order" asp-action="GetAllOrders" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>@localizer["View All Orders"]</a>
                            <a asp-controller="Order" asp-action="GetAllPendingOrder" class="nav-item nav-link"><i class="bi bi-arrow-up-circle-fill me-2"></i>@localizer["Pending Orders"]</a>
                            <a asp-controller="Order" asp-action="GetAllDeliveredOrder" class="nav-item nav-link"><i class="bi bi-cart-check-fill me-2"></i>@localizer["Delivered Orders"]</a>
                            </div>
                        </div>
                    @*Customer Options*@
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-person-check-fill me-2"></i>@localizer["Customers"]</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a class="nav-item nav-link" asp-controller="Customer" asp-action="GetAllUser"> <i class="fa fa-chart-bar me-2"></i>@localizer["View All Users"]</a>
                            <a asp-controller="Customer" asp-action="GetAllUserDeleted" class="nav-item nav-link"><i class="bi bi-person-x-fill me-2"></i>@localizer["Deleted Users"]</a>
                        </div>
                    </div>

                    @*User Option*@
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-people-fill me-2"></i>@localizer["Users"]</a>
                        <div class="dropdown-menu bg-transparent border-0">
                             
                            <a asp-controller="User" asp-action="SignUp" class="nav-item nav-link"><i class="bi bi-person-plus-fill me-2"></i>@localizer["Add User"]</a>
                            <a asp-controller="Role" asp-action="Add" class="nav-item nav-link"><i class="bi bi-asterisk me-2"></i>@localizer["Add Role"]</a>

                        </div>
                    </div>
                 </div>
             </div>
          </nav>
    </div>}


<!-- Sidebar End -->